### ISSUE TITLE
Create Company Card Component

### ISSUE THREAD

**Issue by j-taki** [teleskope/teleskope#14]
Do all work for this task in a branch called issue-

### What is the new behavior (if this is a feature change)?
On the companies index page, companies should appear as cards with limited information so that they can be listed easily. 

## Subtasks
- [x] Create Card component (functional comp. probably)
- [x] Style it so it look very nice
- [x] Apply to Company Index
