### ISSUE TITLE
Deploy on Galaxy

### ISSUE THREAD

**Issue by darius-despain** [teleskope/teleskope#16]
Do all work for this task in a branch called issue-16

## Description
Deploy the project to galaxy prior to Milestone 1 due date

### What is the new behavior (if this is a feature change)?
Application should be deployed to galaxy. Dev should match Prod environments. 
## Subtasks
- [ ] Follow the instructions on the ICS course page for deploying a project to galaxy.  
- [ ] Then take a screen shot of your dashboard and post it to the #deployment Slack channel
- [ ] Add link for deployed application to teleskope.github.io page
Due Wed 10 APR at 2359
