### ISSUE TITLE
Search Bar component

### ISSUE THREAD

**Issue by mattkim009** [teleskope/teleskope#29]
Do all work for this task in a branch called issue-<27>
[Reference for what search bar should do](https://react.semantic-ui.com/modules/search/#variations-fluid)

WHERE SHOULD IT GO??

## Subtasks
- [ ] create SearchBar component file
- [ ] only one option can be selected
- [ ] automatically recommend options as user types

**Comment by j-taki** [comment]
search bar should probably go in the navbar. Also can we update so that the user icon next to the user email shows a student icon if student logged in and building if company logged in.
