### ISSUE TITLE
Create a Student Profile Page

### ISSUE THREAD

**Issue by joshnwalters** [teleskope/teleskope#32]
Do all work for this task in a branch called issue-32

## Subtasks
- [x] Show image of student
- [x] Show a list of skills for the student (mockup for now)
- [x] Show the students experiences, ability to add or delete
- [x] Show the students location
- [x] Show the students preferred work  location
