### ISSUE TITLE
Admin List Students Page

### ISSUE THREAD

**Issue by mattkim009** [teleskope/teleskope#33]
Do all work for this task in a branch called issue-<33>

## Subtasks
- [ ] make the mockup with a edit and delete option
- [ ] add the edit functionality
- [ ] add the delete functionality
