### ISSUE TITLE
Admin List Companies Page

### ISSUE THREAD

**Issue by mattkim009** [teleskope/teleskope#34]
Do all work for this task in a branch called issue-<34>

## Subtasks
- [ ] make the mockup with a edit and delete option
- [ ] add the edit functionality
- [ ] add the delete functionality
