### ISSUE TITLE
Create Show Job page

### ISSUE THREAD

**Issue by joshnwalters** [teleskope/teleskope#39]
Do all work for this task in a branch called issue-39

## Create a page to show an individual job
##Should be the page that is navigated to when a user clicks on an individual job

## Subtasks
- [x] create the layout for the page
- [x] include a link to the application site
- [x] include button to show that it is favorited
