### ISSUE TITLE
Create Company Profile page

### ISSUE THREAD

**Issue by mattkim009** [teleskope/teleskope#41]
Do all work for this task in a branch called issue-41

## Subtasks
- [x] Should be similar to the ShowCompany page
- [x] Show image of company logo (or building or something)
- [x] Show a list of available jobs for the company, should be able to add or delete
- [x] Show the companies location
