### ISSUE TITLE
Student Registration

### ISSUE THREAD

**Issue by j-taki** [teleskope/teleskope#43]
Do all work for this task in a branch called issue-<NUM>

### What is the new behavior (if this is a feature change)?
Students should be able to visit registration page and complete registration. 
Should create new document in users collection
should assign user the role of 'student'
should be visible in students index page. 

## Subtasks
- [x] students schema fix. should not be associated with user anymore. 
- [x] rename students schema to 'profile'
- [x] fix all broken dependencies on students 
- [x] profile should be available to both a company and a student user
- [x] profile gets generated for student/company upon registration. 
- [x] userId gets associated with the owner of the profile on instantiation.
