### ISSUE TITLE
Brand Standards

### ISSUE THREAD

**Issue by j-taki** [teleskope/teleskope#44]
Do all work for this task in a branch called issue-44

### What is the new behavior (if this is a feature change)?
create some new brand standards and apply them to application

## Subtasks
- [x] New Logo
- [x] Primary / secondary colour
- [x] Header / paragraph font
- [x] apply to site
