### ISSUE TITLE
Enhance Skills functionality (Connect with Student)

### ISSUE THREAD

**Issue by mattkim009** [teleskope/teleskope#54]
Do all work for this task in a branch called issue-<54>

## Subtasks
- [x] Student's skills will be recorded

- [x] Make Join table between Skills and student
- [x] Pre-load chosen skills on profile page and ShowStudent page
- [x] Be able to add and delete skills on profile page
