### ISSUE TITLE
User can star a company

### ISSUE THREAD

**Issue by j-taki** [teleskope/teleskope#57]
Do all work for this task in a branch called issue-57

### What is the new behavior (if this is a feature change)?
User clicks the star or interested button on the list /show companies page and it follows that company for updates sent to student's dashboard

when user clicks on star/follow, call meteor method to insert companyId to following on user profile
## Subtasks
- [x] add following to user profile schema
- [x] meteor method for inserting / validation
- [x] link from list-companies
- [x] link from show-company
