### ISSUE TITLE
Hook up user information to Dashboard

### ISSUE THREAD

**Issue by j-taki** [teleskope/teleskope#83]
Do all work for this task in a branch called issue-<NUM>

## Description
user profile should be available on profile page and fill mockup space. 

## Subtasks
- [x] subscribe to UsersProfile 
- [x] fill dashboard with relevant user data
- [x] subscribe to Companies
- [x] if student, get user's followed companies into left column
- [x] if company, get users's owned companies into left column. 

becuase we are goign to be calling companies from notifications feed and from the followed/owned column, we should probably call companies in the smart component('Dashboard'), and then pass a filtered array of companies into each dumber component. 

The database call could be specific enough to only call for followed/owned companies. The way this is designed is dependent on if companies can follow other companies.
