### ISSUE TITLE
Updated pages and components and fixed registration

### ISSUE THREAD

**Issue by mattkim009** [teleskope/teleskope#96]
Do all work for this task in a branch called issue-<96>

## Subtasks
- [x] Updated registration pages with required fields and ZIPcode verification.
- [x] Updated the create profile function and the create company function to initialize every field
- [x] Updated ShowCompany page, ShowStudent page, and Profile page, StudentCard component, and CompanyCard component to handle undefined properties of a Profile object and hyperlinked email address
